nacos:
  discovery:
    client:
      serverList: 127.0.0.1:8848
      namespace: 5f8d158f-c2b0-4d12-bc8b-03496d993dfb
    instance:
      # ip: 127.0.0.1
      port: 3000
      serviceName: discovery
      metadata: null
    subscribes:
      - serviceName: discovery
      - serviceName: discovery-nacos
