proxy:
  extras:
    - timeout: 60000
  routes:
    - id: github
      uri: https://api.github.com
      filters:
        - name: RequestPathFilter
          parameters:
            strip: 2
    - id: app1
      uri: http://127.0.0.1:3000
      filters:
        - name: RequestPathFilter
          parameters:
            strip: 2
            # prefix:
        - name: RequestHeaderFilter
          parameters:
            authorization: Request dGVzdDp0ZXN0
        - name: ResponseHeaderFilter
          parameters:
            authorization: Response dGVzdDp0ZXN0
    - id: app2
      uri: lb://app
      filters:
        - name: RequestPathFilter
          parameters:
            strip: 3
            prefix: /app
        - name: RequestHeaderFilter
          parameters:
            authorization: Request dGVzdDp0ZXN0
        - name: ResponseHeaderFilter
          parameters:
            authorization: Response dGVzdDp0ZXN0

discovery:
  services:
    - name: app
      servers:
        - ip: 127.0.0.1
          port: 3000
