nacos:
  config:
    client:
      serverAddr: 127.0.0.1:8848
      namespace: 5f8d158f-c2b0-4d12-bc8b-03496d993dfb
    configs:
      dataId: config.development.yaml
      group: development
    sharedConfigs:
      dataId: config.yaml
      group: DEFAULT_GROUP
